#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

pre-commit install

python3 -m pip install https://github.com/home-assistant/core/archive/dev.zip